---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linstor-csi-node
  labels:
    app.kubernetes.io/component: linstor-csi-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: linstor-csi-node
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: linstor-csi
      labels:
        app.kubernetes.io/component: linstor-csi-node
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      serviceAccountName: linstor-csi-node
      shareProcessNamespace: true
      hostNetwork: true # For mounting NFS resources
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: system-node-critical
      initContainers:
        - name: linstor-wait-node-online
          image: linstor-csi
          command:
            - /linstor-wait-until
            - satellite-online
            - $(KUBE_NODE_NAME)
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: LS_CONTROLLERS
              value: 'http://linstor-controller:3370'
      containers:
        - name: linstor-csi
          image: linstor-csi
          args:
            - --csi-endpoint=unix://$(ADDRESS)
            - --node=$(KUBE_NODE_NAME)
            - --property-namespace=$(PROPERTY_NAMESPACE)
            - --label-by-storage-pool=$(LABEL_BY_STORAGE_POOL)
          securityContext:
            readOnlyRootFilesystem: true
            privileged: true
            capabilities:
              drop:
                - ALL
              add:
                - SYS_ADMIN
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: PROPERTY_NAMESPACE
              value: Aux/topology
            - name: LABEL_BY_STORAGE_POOL
              value: 'false'
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: LS_CONTROLLERS
              value: 'http://linstor-controller:3370'
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: publish-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: device-dir
              mountPath: /dev
            - name: run-mount
              mountPath: /run/mount
            - name: run-fsck
              mountPath: /run/fsck
            - name: etc-selinux
              mountPath: /etc/selinux
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
        - name: csi-node-driver-registrar
          image: csi-node-driver-registrar
          args:
            - '--v=$(VERBOSE)'
            - '--csi-address=$(ADDRESS)'
            - '--kubelet-registration-path=$(KUBELET_REGISTRATION_PATH)'
            - '--health-port=$(HEALTH_PORT)'
          env:
            - name: VERBOSE
              value: "5"
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBELET_REGISTRATION_PATH
              value: /var/lib/kubelet/plugins/linstor.csi.linbit.com/csi.sock
            - name: HEALTH_PORT
              value: "9809"
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 9809
              name: reg-healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: reg-healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: csi-livenessprobe
          image: csi-livenessprobe
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          args:
            - '--csi-address=$(ADDRESS)'
          env:
            - name: ADDRESS
              value: /csi/csi.sock
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: publish-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: etc-selinux
          hostPath:
            path: /etc/selinux
            type: DirectoryOrCreate
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/linstor.csi.linbit.com
            type: DirectoryOrCreate
        - name: run-mount
          hostPath:
            path: /run/mount
            type: Directory
        - name: run-fsck
          emptyDir: {}
