apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstornodesets.piraeus.linbit.com
spec:
  group: piraeus.linbit.com
  names:
    kind: LinstorNodeSet
    listKind: LinstorNodeSetList
    plural: linstornodesets
    singular: linstornodeset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LinstorNodeSet is the Schema for the linstornodesets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LinstorNodeSetSpec defines the desired state of LinstorNodeSet
          properties:
            priorityClassName:
              description: priorityClassName is the name of the PriorityClass for the node set
              type: string
            drbdKernelModuleInjectionMode:
              description: drbdKernelModuleInjectionMode selects the source for the DRBD kernel module
              type: string
              enum:
              # No module will be injected
              - None
              # The module will be compiled from sources available on the host
              - Compile
              # A module included in the injector image will be used
              - ShippedModules
            storagePools:
              description: StoragePools is a list of StoragePools for LinstorNodeSet
                to manage.
              properties:
                lvmPools:
                  description: LVMPools for LinstorNodeSet to manage.
                  items:
                    description: StoragePoolLVM represents LVM storage pool to be
                      managed by a LinstorNodeSet
                    properties:
                      name:
                        description: Name of the storage pool.
                        type: string
                      volumeGroup:
                        description: Name of underlying lvm group
                        type: string
                    required:
                    - name
                    - volumeGroup
                    type: object
                  type: array
                  nullable: true
                lvmThinPools:
                  description: LVMThinPools for LinstorNodeSet to manage.
                  items:
                    description: StoragePoolLVMThin represents LVM Thin storage pool
                      to be managed by a LinstorNodeSet
                    properties:
                      thinVolume:
                        description: Name of underlying lvm thin volume
                        type: string
                    required:
                    - thinVolume
                    type: object
                  type: array
                  nullable: true
              nullable: true
              type: object
            drbdRepoCred:
              description: DrbdRepoCred is the name of the kubernetes secret that
                holds the credential for the DRBD repositories
              type: string
            satelliteImage:
              description: satelliteImage is the image location for the LINSTOR
                satellite container
              type: string
            satelliteVersion:
              description: satelliteVersion is the image tag/version for the LINSTOR
                satellite container
              type: string
            kernelModImage:
              description: kernelModImage is the image location for the LINSTOR/
                DRBD kernel module injector container
              type: string
            kernelModVersion:
              description: kernelModVersion is the image tag/version for the LINSTOR/
                DRBD kernel module injector container
              type: string
          required:
          - priorityClassName
          - drbdKernelModuleInjectionMode
          - drbdRepoCred
          - satelliteImage
          - satelliteVersion
          - kernelModImage
          - kernelModVersion
          type: object
        status:
          description: LinstorNodeSetStatus defines the observed state of LinstorNodeSet
          properties:
            SatelliteStatuses:
              description: SatelliteStatuses by hostname.
            errors:
              description: Errors remaining that will trigger reconciliations.
              items:
                type: string
              type: array
          required:
          - SatelliteStatuses
          - errors
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
