apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linstorcsidrivers.piraeus.linbit.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.NodeReady
    name: NodeReady
    type: boolean
  - JSONPath: .status.ControllerReady
    name: ControllerReady
    type: boolean
  group: piraeus.linbit.com
  names:
    kind: LinstorCSIDriver
    listKind: LinstorCSIDriverList
    plural: linstorcsidrivers
    singular: linstorcsidriver
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LinstorCSIDriver is the Schema for the linstorcsidrivers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LinstorCSIDriverSpec defines the desired state of LinstorCSIDriver
          properties:
            imagePullSecret:
              description: Name of a secret with authentication details for the `LinstorPluginImage`
                registry
              type: string
            linstorControllerAddress:
              description: Cluster address of the linstor controller
              type: string
            linstorPluginImage:
              description: Image that contains the linstor-csi driver plugin
              type: string
          required:
          - imagePullSecret
          - linstorControllerAddress
          - linstorPluginImage
          type: object
        status:
          description: LinstorCSIDriverStatus defines the observed state of LinstorCSIDriver
          properties:
            ControllerReady:
              description: CSI controller ready status
              type: boolean
            NodeReady:
              description: CSI node components ready status
              type: boolean
            errors:
              description: Errors remaining that will trigger reconciliations.
              items:
                type: string
              type: array
          required:
          - ControllerReady
          - NodeReady
          - errors
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
