// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorSatelliteSet) DeepCopyInto(out *LinstorSatelliteSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorSatelliteSet.
func (in *LinstorSatelliteSet) DeepCopy() *LinstorSatelliteSet {
	if in == nil {
		return nil
	}
	out := new(LinstorSatelliteSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinstorSatelliteSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorSatelliteSetList) DeepCopyInto(out *LinstorSatelliteSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LinstorSatelliteSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorSatelliteSetList.
func (in *LinstorSatelliteSetList) DeepCopy() *LinstorSatelliteSetList {
	if in == nil {
		return nil
	}
	out := new(LinstorSatelliteSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinstorSatelliteSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorSatelliteSetSpec) DeepCopyInto(out *LinstorSatelliteSetSpec) {
	*out = *in
	if in.StoragePools != nil {
		in, out := &in.StoragePools, &out.StoragePools
		*out = new(StoragePools)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorSatelliteSetSpec.
func (in *LinstorSatelliteSetSpec) DeepCopy() *LinstorSatelliteSetSpec {
	if in == nil {
		return nil
	}
	out := new(LinstorSatelliteSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinstorSatelliteSetStatus) DeepCopyInto(out *LinstorSatelliteSetStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SatelliteStatuses != nil {
		in, out := &in.SatelliteStatuses, &out.SatelliteStatuses
		*out = make(map[string]*SatelliteStatus, len(*in))
		for key, val := range *in {
			var outVal *SatelliteStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SatelliteStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinstorSatelliteSetStatus.
func (in *LinstorSatelliteSetStatus) DeepCopy() *LinstorSatelliteSetStatus {
	if in == nil {
		return nil
	}
	out := new(LinstorSatelliteSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatelliteStatus) DeepCopyInto(out *SatelliteStatus) {
	*out = *in
	if in.StoragePoolStatuses != nil {
		in, out := &in.StoragePoolStatuses, &out.StoragePoolStatuses
		*out = make(map[string]*StoragePoolStatus, len(*in))
		for key, val := range *in {
			var outVal *StoragePoolStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(StoragePoolStatus)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatelliteStatus.
func (in *SatelliteStatus) DeepCopy() *SatelliteStatus {
	if in == nil {
		return nil
	}
	out := new(SatelliteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolLVM) DeepCopyInto(out *StoragePoolLVM) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolLVM.
func (in *StoragePoolLVM) DeepCopy() *StoragePoolLVM {
	if in == nil {
		return nil
	}
	out := new(StoragePoolLVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolLVMThin) DeepCopyInto(out *StoragePoolLVMThin) {
	*out = *in
	out.StoragePoolLVM = in.StoragePoolLVM
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolLVMThin.
func (in *StoragePoolLVMThin) DeepCopy() *StoragePoolLVMThin {
	if in == nil {
		return nil
	}
	out := new(StoragePoolLVMThin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolStatus) DeepCopyInto(out *StoragePoolStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolStatus.
func (in *StoragePoolStatus) DeepCopy() *StoragePoolStatus {
	if in == nil {
		return nil
	}
	out := new(StoragePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePools) DeepCopyInto(out *StoragePools) {
	*out = *in
	if in.LVMPools != nil {
		in, out := &in.LVMPools, &out.LVMPools
		*out = make([]*StoragePoolLVM, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StoragePoolLVM)
				**out = **in
			}
		}
	}
	if in.LVMThinPools != nil {
		in, out := &in.LVMThinPools, &out.LVMThinPools
		*out = make([]*StoragePoolLVMThin, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StoragePoolLVMThin)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePools.
func (in *StoragePools) DeepCopy() *StoragePools {
	if in == nil {
		return nil
	}
	out := new(StoragePools)
	in.DeepCopyInto(out)
	return out
}
