---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linstor-csi-node-tls
spec:
  issuerRef:
    name: FILLME
  secretName: linstor-csi-node-tls
  commonName: linstor-csi-node
  usages:
    - "client auth"
