---
# This is the configuration for default images used by piraeus-operator
#
# "base" is the default repository prefix to use.
base: quay.io/piraeusdatastore
# "components" is a mapping of image placeholders to actual image names with tag.
# For example, the image name "linstor-controller" in the kustomize-resources will be replaced by:
#   quay.io/piraeusdatastore/piraeus-server:v1.24.2
components:
  linstor-controller:
    tag: v1.26.2
    image: piraeus-server
  linstor-satellite:
    tag: v1.26.2
    image: piraeus-server
  linstor-csi:
    tag: v1.4.0
    image: piraeus-csi
  drbd-reactor:
    tag: v1.4.0
    image: drbd-reactor
  ha-controller:
    tag: v1.2.0
    image: piraeus-ha-controller
  drbd-shutdown-guard:
    tag: v1.0.0
    image: drbd-shutdown-guard
  ktls-utils:
    tag: v0.10
    image: ktls-utils
  drbd-module-loader:
    tag: v9.2.8
    # The special "match" attribute is used to select an image based on the node's reported OS.
    # The operator will first check the k8s node's ".status.nodeInfo.osImage" field, and compare it against the list
    # here. If one matches, that specific image name will be used instead of the fallback image.
    image: drbd9-jammy # Fallback image: chose a fairly recent kernel, which can hopefully compile whatever config is actually in use
    match:
      - osImage: CentOS Linux 7
        image: drbd9-centos7
      - osImage: CentOS Linux 8
        image: drbd9-centos8
      - osImage: AlmaLinux 8
        image: drbd9-almalinux8
      - osImage: Red Hat Enterprise Linux CoreOS
        image: drbd9-almalinux8
      - osImage: AlmaLinux 9
        image: drbd9-almalinux9
      - osImage: Rocky Linux 8
        image: drbd9-almalinux8
      - osImage: Rocky Linux 9
        image: drbd9-almalinux9
      - osImage: Ubuntu 18\.04
        image: drbd9-bionic
      - osImage: Ubuntu 20\.04
        image: drbd9-focal
      - osImage: Ubuntu 22\.04
        image: drbd9-jammy
      - osImage: Debian GNU/Linux 12
        image: drbd9-bookworm
      - osImage: Debian GNU/Linux 11
        image: drbd9-bullseye
      - osImage: Debian GNU/Linux 10
        image: drbd9-buster
