---
base: registry.k8s.io/sig-storage
components:
  csi-attacher:
    tag: v4.7.0
    image: csi-attacher
  csi-livenessprobe:
    tag: v2.14.0
    image: livenessprobe
  csi-provisioner:
    tag: v5.1.0
    image: csi-provisioner
  csi-snapshotter:
    tag: v8.1.0
    image: csi-snapshotter
  csi-resizer:
    tag: v1.12.0
    image: csi-resizer
  csi-external-health-monitor-controller:
    tag: v0.13.0
    image: csi-external-health-monitor-controller
  csi-node-driver-registrar:
    tag: v2.12.0
    image: csi-node-driver-registrar
