---
base: registry.k8s.io/sig-storage
components:
  csi-attacher:
    tag: v4.6.1
    image: csi-attacher
  csi-livenessprobe:
    tag: v2.13.1
    image: livenessprobe
  csi-provisioner:
    tag: v5.0.1
    image: csi-provisioner
  csi-snapshotter:
    tag: v8.0.1
    image: csi-snapshotter
  csi-resizer:
    tag: v1.11.1
    image: csi-resizer
  csi-external-health-monitor-controller:
    tag: v0.12.1
    image: csi-external-health-monitor-controller
  csi-node-driver-registrar:
    tag: v2.11.1
    image: csi-node-driver-registrar
