---
base: registry.k8s.io/sig-storage
components:
  csi-attacher:
    tag: v4.5.0
    image: csi-attacher
  csi-livenessprobe:
    tag: v2.12.0
    image: livenessprobe
  csi-provisioner:
    tag: v4.0.0
    image: csi-provisioner
  csi-snapshotter:
    tag: v7.0.1
    image: csi-snapshotter
  csi-resizer:
    tag: v1.10.0
    image: csi-resizer
  csi-external-health-monitor-controller:
    tag: v0.11.0
    image: csi-external-health-monitor-controller
  csi-node-driver-registrar:
    tag: v2.10.0
    image: csi-node-driver-registrar
