---
base: registry.k8s.io/sig-storage
components:
  csi-attacher:
    tag: v4.12.0
    image: csi-attacher
  csi-livenessprobe:
    tag: v2.19.0
    image: livenessprobe
  csi-provisioner:
    tag: v6.3.0
    image: csi-provisioner
  csi-snapshotter:
    tag: v8.6.0
    image: csi-snapshotter
  csi-resizer:
    tag: v2.2.1
    image: csi-resizer
  csi-external-health-monitor-controller:
    tag: v0.18.0
    image: csi-external-health-monitor-controller
  csi-node-driver-registrar:
    tag: v2.17.0
    image: csi-node-driver-registrar
