resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - images.yaml
  name: image-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
