---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linstor-csi-controller
  labels:
    app.kubernetes.io/component: linstor-csi-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: linstor-csi-controller
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: linstor-csi
      labels:
        app.kubernetes.io/component: linstor-csi-controller
    spec:
      enableServiceLinks: false
      serviceAccountName: linstor-csi-controller
      shareProcessNamespace: true
      priorityClassName: system-node-critical
      initContainers:
        - name: linstor-wait-api-online
          image: linstor-csi
          command:
            - /linstor-wait-until
            - api-online
          env:
            - name: LS_CONTROLLERS
              value: 'http://linstor-controller:3370'
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      containers:
        - name: linstor-csi
          image: linstor-csi
          args:
            - --csi-endpoint=unix://$(ADDRESS)
            - --property-namespace=$(PROPERTY_NAMESPACE)
            - --label-by-storage-pool=$(LABEL_BY_STORAGE_POOL)
            - --enable-rwx=$(ENABLE_RWX)
            - --nfs-reactor-config-map-name=$(NFS_REACTOR_CONFIG_MAP_NAME)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: PROPERTY_NAMESPACE
              value: Aux/topology
            - name: LABEL_BY_STORAGE_POOL
              value: 'false'
            - name: ENABLE_RWX
              value: 'true'
            - name: NFS_REACTOR_CONFIG_MAP_NAME
              value: linstor-csi-nfs-server-reactor-config
            - name: LS_CONTROLLERS
              value: 'http://linstor-controller:3370'
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          ports:
            - name: healthz
              containerPort: 9808
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: csi-attacher
          image: csi-attacher
          args:
            - '--v=$(VERBOSE)'
            - '--csi-address=$(ADDRESS)'
            - '--timeout=$(TIMEOUT)'
            - '--leader-election=$(LEADER_ELECTION)'
            - '--leader-election-namespace=$(NAMESPACE)'
            - '--worker-threads=$(WORKER_THREADS)'
            - '--http-endpoint=$(HTTP_ENDPOINT)'
          env:
            - name: VERBOSE
              value: "5"
            - name: ADDRESS
              value: /csi/csi.sock
            - name: TIMEOUT
              value: "1m"
            - name: LEADER_ELECTION
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: WORKER_THREADS
              value: "10"
            - name: HTTP_ENDPOINT
              value: :9809
          livenessProbe:
            httpGet:
              port: 9809
              path: /healthz/leader-election
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: csi-livenessprobe
          image: csi-livenessprobe
          args:
            - '--csi-address=$(ADDRESS)'
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: csi-provisioner
          image: csi-provisioner
          args:
            - '--v=$(VERBOSE)'
            - '--csi-address=$(ADDRESS)'
            - '--timeout=$(TIMEOUT)'
            - '--leader-election=$(LEADER_ELECTION)'
            - '--leader-election-namespace=$(NAMESPACE)'
            - '--worker-threads=$(WORKER_THREADS)'
            - '--http-endpoint=$(HTTP_ENDPOINT)'
            - '--default-fstype=$(DEFAULT_FS_TYPE)'
            - '--enable-capacity=$(ENABLE_CAPACITY)'
            - '--extra-create-metadata=$(EXTRA_CREATE_METADATA)'
            - '--capacity-ownerref-level=$(CAPACITY_OWNERREF_LEVEL)'
          env:
            - name: VERBOSE
              value: "5"
            - name: ADDRESS
              value: /csi/csi.sock
            - name: TIMEOUT
              value: "1m"
            - name: LEADER_ELECTION
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: WORKER_THREADS
              value: "10"
            - name: HTTP_ENDPOINT
              value: :9810
            - name: DEFAULT_FS_TYPE
              value: ext4
            - name: ENABLE_CAPACITY
              value: "true"
            - name: EXTRA_CREATE_METADATA
              value: "true"
            - name: CAPACITY_OWNERREF_LEVEL
              value: "2"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              port: 9810
              path: /healthz/leader-election
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: csi-snapshotter
          image: csi-snapshotter
          args:
            - '--v=$(VERBOSE)'
            - '--csi-address=$(ADDRESS)'
            - '--timeout=$(TIMEOUT)'
            - '--leader-election=$(LEADER_ELECTION)'
            - '--leader-election-namespace=$(NAMESPACE)'
            - '--worker-threads=$(WORKER_THREADS)'
            - '--http-endpoint=$(HTTP_ENDPOINT)'
            - '--feature-gates=CSIVolumeGroupSnapshot=$(FEATURE_GATE_CSI_VOLUME_GROUP_SNAPSHOT),$(FEATURE_GATES)'
          env:
            - name: VERBOSE
              value: "5"
            - name: ADDRESS
              value: /csi/csi.sock
            - name: TIMEOUT
              value: "1m"
            - name: LEADER_ELECTION
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: WORKER_THREADS
              value: "10"
            - name: HTTP_ENDPOINT
              value: :9811
            - name: FEATURE_GATE_CSI_VOLUME_GROUP_SNAPSHOT
              value: "true"
            - name: FEATURE_GATES
              value: ""
          livenessProbe:
            httpGet:
              port: 9811
              path: /healthz/leader-election
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: csi-resizer
          image: csi-resizer
          args:
            - '--v=$(VERBOSE)'
            - '--csi-address=$(ADDRESS)'
            - '--timeout=$(TIMEOUT)'
            - '--leader-election=$(LEADER_ELECTION)'
            - '--leader-election-namespace=$(NAMESPACE)'
            - '--workers=$(WORKER_THREADS)' # the only one using a different name
            - '--http-endpoint=$(HTTP_ENDPOINT)'
            - '--handle-volume-inuse-error=$(HANDLE_VOLUME_INUSE_ERROR)'
          env:
            - name: VERBOSE
              value: "5"
            - name: ADDRESS
              value: /csi/csi.sock
            - name: TIMEOUT
              value: "1m"
            - name: LEADER_ELECTION
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: WORKER_THREADS
              value: "10"
            - name: HTTP_ENDPOINT
              value: :9812
            - name: HANDLE_VOLUME_INUSE_ERROR
              value: "false"
          livenessProbe:
            httpGet:
              port: 9812
              path: /healthz/leader-election
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: csi-health-monitor
          image: csi-external-health-monitor-controller
          args:
            - '--v=$(VERBOSE)'
            - '--csi-address=$(ADDRESS)'
            - '--timeout=$(TIMEOUT)'
            - '--leader-election=$(LEADER_ELECTION)'
            - '--leader-election-namespace=$(NAMESPACE)'
            - '--worker-threads=$(WORKER_THREADS)'
            - '--http-endpoint=$(HTTP_ENDPOINT)'
          env:
            - name: VERBOSE
              value: "5"
            - name: ADDRESS
              value: /csi/csi.sock
            - name: TIMEOUT
              value: "1m"
            - name: LEADER_ELECTION
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: WORKER_THREADS
              value: "10"
            - name: HTTP_ENDPOINT
              value: :9813
          livenessProbe:
            httpGet:
              port: 9813
              path: /healthz/leader-election
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: socket-dir
          emptyDir: {}
