---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linstor-api-tls
spec:
  issuerRef:
    name: FILLME
  secretName: linstor-api-tls
  dnsNames:
    - linstor-controller.piraeus-datastore.svc.cluster.local
    - linstor-controller.piraeus-datastore.svc
    - linstor-controller
  usages:
    - "server auth"
