---
apiVersion: v1
kind: Pod
metadata:
  name: satellite
  annotations:
    kubectl.kubernetes.io/default-container: linstor-satellite
  labels:
    app.kubernetes.io/component: linstor-satellite
spec:
  automountServiceAccountToken: false
  enableServiceLinks: false
  serviceAccountName: satellite
  initContainers:
    - name: drbd-module-loader
      image: drbd-module-loader
      env:
        - name: LB_FAIL_IF_USERMODE_HELPER_NOT_DISABLED
          value: "yes"
        - name: LB_SELINUX_AS
          value: "modules_object_t"
      securityContext:
        readOnlyRootFilesystem: true
        seLinuxOptions:
          # "super privileged container"_t to allow changing of labels if required
          type: spc_t
          level: s0
        capabilities:
          drop:
            - ALL
          add:
            - SYS_MODULE
      volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /usr/src
          name: usr-src
          readOnly: true
        - mountPath: /tmp
          name: tmp
    - name: drbd-shutdown-guard
      image: drbd-shutdown-guard
      securityContext:
        privileged: true
        readOnlyRootFilesystem: true
      volumeMounts:
        - mountPath: /run/systemd/system/
          name: run-systemd-system
        - mountPath: /run/drbd-shutdown-guard
          name: run-drbd-shutdown-guard
        - mountPath: /run/dbus/system_bus_socket
          name: systemd-bus-socket
  containers:
    - name: linstor-satellite
      image: linstor-satellite
      args:
        - startSatellite
      env:
        - name: JAVA_OPTS
          value: -Djdk.tls.acknowledgeCloseNotify=true
      securityContext:
        readOnlyRootFilesystem: true
        privileged: true
        capabilities:
          drop:
            - ALL
          add:
            - NET_ADMIN
            - SYS_ADMIN
      volumeMounts:
        - mountPath: /etc/linstor
          name: satellite-config
          readOnly: true
        - mountPath: /dev
          name: dev
        - mountPath: /var/log/linstor-satellite
          name: var-log-linstor-satellite
        - mountPath: /var/lib/drbd
          name: var-lib-drbd
        - mountPath: /var/lib/linstor.d
          name: var-lib-linstor-d
        - mountPath: /etc/lvm/archive
          name: etc-lvm-archive
        - mountPath: /etc/lvm/backup
          name: etc-lvm-backup
        - mountPath: /run
          name: run
        - mountPath: /tmp
          name: tmp
        - mountPath: /run/lock
          name: run-lock
    - name: drbd-reactor
      image: drbd-reactor
      ports:
        - name: prometheus
          containerPort: 9942
          protocol: TCP
      securityContext:
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - mountPath: /etc/drbd-reactor.d
          name: reactor-config
          readOnly: true
  volumes:
    - name: lib-modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: usr-src
      hostPath:
        path: /usr/src
        type: Directory
    - name: dev
      hostPath:
        path: /dev
        type: Directory
    - name: etc-lvm-archive
      hostPath:
        path: /etc/lvm/archive
        type: DirectoryOrCreate
    - name: etc-lvm-backup
      hostPath:
        path: /etc/lvm/backup
        type: DirectoryOrCreate
    - name: var-lib-linstor-d
      hostPath:
        path: /var/lib/linstor.d
        type: DirectoryOrCreate
    - name: var-lib-drbd
      hostPath:
        path: /var/lib/drbd
        type: DirectoryOrCreate
    - name: run-systemd-system
      hostPath:
        path: /run/systemd/system/
        type: Directory
    - name: run-drbd-shutdown-guard
      hostPath:
        path: /run/drbd-shutdown-guard
        type: DirectoryOrCreate
    - name: systemd-bus-socket
      hostPath:
        path: /run/dbus/system_bus_socket
        type: Socket
    - name: var-log-linstor-satellite
      hostPath:
        path: /var/log/linstor-satellite
        type: DirectoryOrCreate
    - name: satellite-config
      configMap:
        name: satellite-config
        defaultMode: 0440
    - name: reactor-config
      configMap:
        name: reactor-config
        defaultMode: 0440
    - name: tmp
      emptyDir: { }
    - name: run-lock
      emptyDir: { }
    - name: run
      emptyDir: { }
  restartPolicy: Always
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
    - key: node.kubernetes.io/not-ready
      effect: NoExecute
    - key: node.kubernetes.io/unreachable
      effect: NoExecute
    - key: node.kubernetes.io/disk-pressure
      effect: NoSchedule
    - key: node.kubernetes.io/memory-pressure
      effect: NoSchedule
    - key: node.kubernetes.io/unschedulable
      effect: NoSchedule
    - key: drbd.linbit.com/lost-quorum
      effect: NoSchedule
    - key: drbd.linbit.com/force-io-error
      effect: NoSchedule
