---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linstor-controller
  namespace: system
  labels:
    app.kubernetes.io/component: linstor-controller
spec:
  endpoints:
    - port: api
      scheme: http
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: linstor-controller
