---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: satellite
  labels:
    app.kubernetes.io/component: linstor-satellite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: satellite
  labels:
    app.kubernetes.io/component: linstor-satellite
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: satellite
  labels:
    app.kubernetes.io/name: linstor-satellite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: satellite
subjects:
  - kind: ServiceAccount
    name: satellite
