---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-csi-node
  labels:
    app.kubernetes.io/component: linstor-csi-node
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linstor-csi-node
  labels:
    app.kubernetes.io/component: linstor-csi-node
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linstor-csi-node
  labels:
    app.kubernetes.io/name: linstor-csi-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linstor-csi-node
subjects:
  - kind: ServiceAccount
    name: linstor-csi-node
