apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: piraeus-operator
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: piraeus-operator
