# permissions for end users to view linstorsatellites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linstorsatellite-viewer-role
rules:
- apiGroups:
  - piraeus.io
  resources:
  - linstorsatellites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - piraeus.io
  resources:
  - linstorsatellites/status
  verbs:
  - get
