# permissions for end users to edit linstornodeconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: linstornodeconnection-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: piraeus-operator
    app.kubernetes.io/part-of: piraeus-operator
    app.kubernetes.io/managed-by: kustomize
  name: linstornodeconnection-editor-role
rules:
- apiGroups:
  - piraeus.io
  resources:
  - linstornodeconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - piraeus.io
  resources:
  - linstornodeconnections/status
  verbs:
  - get
