# permissions for end users to view linstorsatelliteconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linstorsatelliteconfiguration-viewer-role
rules:
- apiGroups:
  - piraeus.io
  resources:
  - linstorsatelliteconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - piraeus.io
  resources:
  - linstorsatelliteconfigurations/status
  verbs:
  - get
