# permissions for end users to view linstorclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linstorcluster-viewer-role
rules:
- apiGroups:
  - piraeus.io
  resources:
  - linstorclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - piraeus.io
  resources:
  - linstorclusters/status
  verbs:
  - get
