= Helm Reference Table

== Global Settings

=== `drbdRepoCred`

Default:: `""`
Valid values:: secret name
Description:: Names a secret containing registry credentials to pull LINSTOR container images.

=== `global.imagePullPolicy`
Default:: `IfNotPresent`
Valid values::
* `""`
* `Always`
* `IfNotPresent`
* `Never`
Description:: Global pull policy to apply to all images. Can be set to `""` to use kubernetes default behaviour. See https://kubernetes.io/docs/concepts/containers/images/#updating-images[pull policy].

=== `global.setSecurityContext`
Default:: `True`
Valid values::
* `True`
* `False`
Description:: If true, all non-privileged containers start with a fixed UID of 1000 and GID of 1000.

=== `linstorHttpsClientSecret`
Default:: `""`
Valid values:: secret name
Description:: References the secret to use when configuring LINSTOR clients to use HTTPS. Check out link:./security.md#configuring-secure-communications-for-the-linstor-api[the security guide]

=== `linstorHttpsControllerSecret`
Default:: `""`
Valid values:: secret name
Description:: References the secret to use when configuring LINSTOR contoller to use HTTPS. Check out link:./security.md#configuring-secure-communications-for-the-linstor-api[the security guide]

=== `priorityClassName`
Default:: `""`
Valid values:: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass[priority class] name
Description:: Name of the priority class with which the LINSTOR components should be scheduled.

=== `controllerEndpoint`
Default:: `""`
Valid values:: HTTP/S URL
Description:: Override the generated URL for the LINSTOR controller deployment. Useful if the controller is not deployed via the operator.

== Operator

=== `operator.image`
Default:: `quay.io/piraeusdatastore/piraeus-operator:<tag>`
Valid values:: image ref
Description:: Image to use for the operator deployment.

Note: prefer to use a pinned version (i.e. `:v1.0.0`) over a rolling tag (i.e. `:latest`). During development, the default value will be `:latest`, on release it will match the release tag.

=== `operator.replicas`
Default:: `1`
Valid values:: number
Description:: Number of replicas of the operator.

=== `operator.resources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the operator containers.

=== `operator.podsecuritycontext`
Default:: `{}`
Valid values:: A valid pod-level https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security-context]
Description:: Override for the default security context passed to the operator pods. See <<_global_setsecuritycontext>>

=== `operator.affinity`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[affinity]
Description:: Set the operator pod affinity. The default expands to allow only one operator pod per node.

=== `operator.tolerations`
Default:: `[]`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[tolerations]
Description:: Tolerations to pass to the operator pod.




== CSI Driver

=== `csi.controllerAffinity`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[affinity]
Description:: Affinity settings for controller pods. Can be used to pin controller pods to specific nodes. The default will expand to:
+
[source,yaml]
----
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: piraeus
          role: csi-controller
      topologyKey: kubernetes.io/hostname
----
+
To not use any affinity settings, set the value to `nodeAffinity: {}`

=== `csi.controllerReplicas`
Default:: `1`
Valid values:: number
Description:: Number of replicas for the LINSTOR CSI controller.

=== `csi.controllerTolerations`
Default:: `[]`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[tolerations]
Description:: Tolerations to pass to the LINSTOR CSI controller.

=== `csi.csiAttacherImage`
Default:: `k8s.gcr.io/sig-storage/csi-attacher:v3.0.2`
Valid values:: image ref
Description:: Image to use for LINSTOR CSI's attacher container: https://kubernetes-csi.github.io/docs/external-attacher.html[csi docs]

=== `csi.livenessProbeImage`
Default:: `k8s.gcr.io/sig-storage/livenessprobe:v2.1.0`
Valid values:: image ref
Description: Image to use for LINSTOR CSI's liveness probe: https://kubernetes-csi.github.io/docs/livenessprobe.html

=== `csi.csiNodeDriverRegistrarImage`
Default:: `k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1`
Valid values:: image ref
Description:: Image to use for LINSTOR CSI's node registrar container: https://kubernetes-csi.github.io/docs/node-driver-registrar.html[csi docs]

=== `csi.csiProvisionerImage`
Default:: `k8s.gcr.io/sig-storage/csi-provisioner:v2.0.4`
Valid values:: image ref
Description:: Image to use for LINSTOR CSI's provision container: https://kubernetes-csi.github.io/docs/external-provisioner.html[csi docs]

=== `csi.csiResizerImage`
Default:: `k8s.gcr.io/sig-storage/csi-resizer:v1.0.1`
Valid values:: image ref
Description:: Image to use for LINSTOR CSI's resizer container: https://kubernetes-csi.github.io/docs/external-resizer.html[csi docs]

=== `csi.csiSnapshotterImage`
Default:: `k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.2`
Valid values:: image ref
Description:: Image to use for LINSTOR CSI's snapshotter container: https://kubernetes-csi.github.io/docs/external-snapshotter.html[csi docs]

=== `csi.enabled`
Default:: `True`
Valid values::
* `True`
* `False`
Description:: Enable deployment of the LINSTOR CSI driver.

=== `csi.enableTopology`
Default:: `False`
Value values::
* `True`
* `False`
Description:: Enable the CSI Topology feature. This feature ensures that pods are always assigned to nodes that can
access persistent volumes. This is especially important for volumes without a networking layer (DRBD).

=== `csi.nodeAffinity`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[affinity]
Description:: Affinity settings for node pods. Can be used to restrict csi pods to specific nodes.

=== `csi.nodeTolerations`
Default:: `[]`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[tolerations]
Description:: Tolerations to pass to the csi node pods.

=== `csi.pluginImage`
Default:: `quay.io/piraeusdatastore/piraeus-csi:v0.18.0`
Valid values:: image ref
Description:: Image to use for LINSTOR CSI plugin containers (both node and controller). https://github.com/piraeusdatastore/linstor-csi[Project page]

=== `csi.resources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the CSI driver pods.

Note: This will apply to every container individually, their resource usage is quite similar.

=== `csi.kubeletPath`
Default:: `/var/lib/kubelet`
Valid values:: string
Description:: Path to the working directory of kubelet. Some distributions require changing this path for CSI to work.
See link:distributions.md[here] for more information

=== `csi.logLevel`
Default:: `""`
Valid values:: `error`, `warn`, `info`, `debug`, `trace`
Description:: Set the log level of the LINSTOR CSI driver. If not set defaults to `info`.

=== `csi.csiAttacherWorkerThreads`
Default:: `10`
Valid values:: Positive integer
Description:: Number of simultaneously running operations for attaching and detaching volumes.

=== `csi.csiProvisionerWorkerThreads`
Default:: `10`
Valid values:: Positive integer
Description:: Number of simultaneously running operations for creating and deleting volumes.

=== `csi.csiSnapshotterWorkerThreads`
Default:: `10`
Valid values:: Positive integer
Description:: Number of simultaneously running operations for creating and deleting snapshots.

=== `csi.csiResizerWorkerThreads`
Default:: `10`
Valid values:: Positive integer
Description:: Number of simultaneously running operations for resizing volumes.

== ETCD

=== `etcd.image.repository`
Default:: `gcr.io/etcd-development/etcd`
Valid values:: image name
Description:: Image name for etcd. Will be joined with `.tag`.

=== `etcd.image.tag`
Default:: `v3.4.9`
Valid values:: image tag
Description:: Image tag for etcd. Will be joined with `.repository`.

=== `etcd.persistentVolume.enabled`
Default:: `True`
Valid values::
* `True`
* `False`
Description:: Use persistent volumes for etcd. Requires private volumes to be available outside of linstor.

=== `etcd.persistentVolume.storage`
Default:: `1Gi`
Valid values:: resource unit
Description:: Size of the volume claim use to store etcd data.

=== `etcd.replicas`
Default:: `1`
Valid values:: number
Description:: number of replicas to use for ETCD. An odd number is preferred.

=== `etcd.affinity`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[affinity]
Description:: Affinity settings for etcd pods. The default allows scheduling on master nodes.

=== `etcd.resources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the etcd containers. See https://etcd.io/docs/v3.4.0/faq/#system-requirements[etcd docs]

=== `etcd.tolerations`
Default::
[source]
----
- key: node-role.kubernetes.io/master
  operator: "Exists"
  effect: "NoSchedule"
----
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[tolerations]
Description:: Set the tolerations for etcd. Defaults to allow scheduling on master nodes.

=== `etcd.podsecuritycontext`
Default:: `{}`
Valid values:: A valid pod-level https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security-context]
Description:: Override for the default security context passed to the etcd pods. See <<_global_setsecuritycontext>>

=== `etcd.priorityClassName`
Default: `""`
Valid values:: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass[priority class] name
Description:: Name of the priority class with which the Etcd pods should be scheduled.

== Piraeus Controller

=== `operator.controller.enabled`
Default:: `True`
Valid values::
* `True`
* `False`
Description:: If set to false, no LinstorController resource will be created by Helm. This means no LINSTOR controller will be deployed.

=== `operator.controller.affinity`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[affinity]
Description:: Affinity settings for controller pods. Can be used to restrict the pods to specific nodes. The default will expand to:
+
[source,yaml]
----
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app: piraeus-op
          role: piraeus-controller
      topologyKey: kubernetes.io/hostname
----
+
To not use any affinity settings, set the value to `nodeAffinity: {}`

=== `operator.controller.controllerImage`
Default:: `quay.io/piraeusdatastore/piraeus-server:v1.12.3`
Valid values:: image ref
Description:: Name of the image to use for the controller.

=== `operator.controller.dbCertSecret`
Default:: `""`
Valid values:: secret name
Description:: Name of the secret that contains the necessary values for securely connecting to the database. Check link:./security.md#secure-communication-with-an-existing-etcd-instance[the security guide].

=== `operator.controller.dbUseClientCert`
Default:: `False`
Valid values::
* `True`
* `False`
Description:: Enable to use client certificates when authenticating on the database. Check link:./security.md#authentication-with-etcd-using-certificates[the security guide].

=== `operator.controller.luksSecret`
Default:: `""`
Valid values:: secret name
Description:: Name of the secret that contains the master passphrase LINSTOR uses for encrypted volumes and securing secrets. Check link:./security.md#automatically-set-the-passphrase-for-linstor[the security guide].
+
If not specified, a random passphrase will be created by helm.

=== `operator.controller.replicas`
Default:: `1`
Valid values:: number
Description:: Number of replicas to use for the Linstor controller.

=== `operator.controller.resources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the controller containers.

Note: at least 750MiB memory is recommended.

=== `operator.controller.sslSecret`
Default:: `""`
Valid values:: secret name
Description:: Name of the secret to use for secure communication between controller and satellites. Check link:./security.md#configuring-secure-communication-between-linstor-components[the security guide].

=== `operator.controller.tolerations`
Default:: `[]`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[tolerations]
Description:: Tolerations to pass to the controller pods.


=== `operator.controller.additonalEnv`
Default:: `[]`
Valid values:: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/[EnvVar list]
Description:: A list of additional environment variables to pass to the Linstor controller container.


=== `operator.controller.additionalProperties`
Default:: `{}`
Valid values:: A map with string keys and values
Description:: A map of properties to set on the Linstor Controller, equivalent to
calling `linstor controller set-property <key> <value>`

=== `operator.controller.logLevel`
Default:: `""`
Valid values:: `error`, `warn`, `info`, `debug`, `trace`
Description:: Set the log level of the LINSTOR Controller. If not set defaults to `info`.

== Piraeus Satellites

=== `operator.satelliteSet.enabled`
Default:: `True`
Valid values::
* `True`
* `False`
Description:: If set to false, no LinstorSatelliteSet resource will be created by Helm. This means no LINSTOR satellites will be deployed.

=== `operator.satelliteSet.affinity`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[affinity]
Description:: Affinity settings for satellite pods. Can be used to restrict the pods to specific nodes.

=== `operator.satelliteSet.automaticStorageType`
Default::  `None`
Valid values::
* `None`
* `LVM`
* `LVMTHIN`
* `ZFS`
Description::  Automatically create storage pools of the specified type. Check the link:./storage.md#preparing-physical-devices[storage guide].

* `None`: no automatic set up (default)
* `LVM`: create a LVM (thick) storage pool
* `LVMTHIN`: create a LVM thin storage pool
* `ZFS`: create a ZFS based storage pool

=== `operator.satelliteSet.kernelModuleInjectionImage`
Default:: `quay.io/piraeusdatastore/drbd9-bionic:v9.0.29`
Valid values:: image ref
Description:: Name of the image to use for loading kernel modules. This is specific to the nodes host system. Check https://quay.io/organization/piraeusdatastore[the available `drbd9` images]

=== `operator.satelliteSet.kernelModuleInjectionMode`
Default:: `Compile`
Valid values::
* `None`
* `Compile`
* `ShippedModules`
* `DepsOnly`
Description::  Determine how the required kernel modules are injected in the host kernel

* `None`: disable module injection (deprecated, use `DepsOnly` instead)
* `Compile`: will compile DRBD from source and load the other modules from the host
* `ShippedModules`: loads a pre-built DRBD from the container
* `DepsOnly`: will only load modules from the host without DRBD

=== `operator.satelliteSet.kernelModuleInjectionResources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the kernel module injection init containers.

Note: When using `kernelModuleInjectionMode: Compile`, at least 500MiB of memory is required.

=== `operator.satelliteSet.kernelModuleInjectionAdditionalSourceDirectory`
Default:: `""`, implying /usr/src.
Valid values:: Existing (absolute) filesystem path or "none".
Description:: Path to the directory holding the kernel source, required when compiling DRBD. If not set, it defaults
to `/usr/src`, which is the kernel source path on most distributions. In some cases, you might need to disable this by
using `"none"` as the directory (more generally: any non-absolute path will result in _no_ mount).

=== `operator.satelliteSet.monitoringImage`
Default:: `quay.io/piraeusdatastore/drbd-reactor:v0.3.0`
Valid values:: iamge ref
Description:: Image to use for exporting monitoring information. Expects an image that runs `drbd-reactor`, with
configuration placed in `/etc/drbd-reactor.d/`.

=== `operator.satelliteSet.resources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the satellite containers.

Note: at least 750MiB memory is recommended.

=== `operator.satelliteSet.satelliteImage`
Default:: `quay.io/piraeusdatastore/piraeus-server:v1.12.3`
Valid values:: image ref
Description:: Name of the image to use for the satellites.

=== `operator.satelliteSet.sslSecret`
Default:: `""`
Valid values:: secret name
Description:: Name of the secret to use for secure communication between controller and satellites. Check link:./security.md#configuring-secure-communication-between-linstor-components[the security guide].

=== `operator.satelliteSet.storagePools`
Default:: `{}`
Valid values:: map
Description:: See the link:./storage.md#configuring-storage-pool-creation[guide on storage pool creation]

=== `operator.satelliteSet.tolerations`
Default:: `[]`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[tolerations]
Description:: Tolerations to pass to the satellite pods.

=== `operator.satelliteSet.additonalEnv`
Default:: `[]`
Valid values:: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/[EnvVar list]
Description:: A list of additional environment variables to pass to the Linstor satellite containers.

=== `operator.satelliteSet.logLevel`
Default:: `""`
Valid values:: `error`, `warn`, `info`, `debug`, `trace`
Description:: Set the log level of the LINSTOR Satellite. If not set defaults to `info`.

== PSP

=== `psp.privilegedRole`
Default:: `""`
Valid values:: role name
Description:: All service accounts of pods that need to run as privileged containers will be bound to this role.
+
Currently, two components require this:
+
- csi-nodes
- linstor-satellites
+
They require:
- running as root (UID 0)
- running as privileged containers
- the `SYS_ADMIN` capability

=== `psp.unprivilegedRole`
Default:: `""`
Valid values:: role name
Description:: All service accounts of pods that do not require special privileges will be bound to this role.

== Stork Scheduler

=== `stork.enabled`
Default:: `True`
Valid values::
* `True`
* `False`
Description:: Enable deployment of stork scheduler

=== `stork.replicas`
Default:: `1`
Valid values:: number
Description:: Number of replicas for both stork plugin and kube-scheduler pods.

=== `stork.schedulerResources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the kube scheduler containers.

=== `stork.schedulerImage`
Default:: `k8s.gcr.io/kube-scheduler-amd64`
Valid values:: image name
Description:: (Base) name of the kube-scheduler image. Will be joined with `schedulerTag`

=== `stork.schedulerTag`
Default:: `""`
Valid values:: image tag
Description:: Tag of the scheduler image to use. If left empty, will default to the tag matching the kubernetes version.

=== `stork.storkImage`
Default:: `docker.io/openstorage/stork:2.5.0`
Valid values:: image ref
Description:: Name of the image to use for the stork plugin

=== `stork.storkResources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the stork containers.

=== `stork.podsecuritycontext`
Default:: `{}`
Valid values:: A valid pod-level https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security-context]
Description:: Override for the default security context passed to the stork and scheduler pods. See <<_global_setsecuritycontext>>

== High Availability Controller

=== `haController.enabled`
Default:: `true`
Valid values::
* `True`
* `False`
Description:: Enable deployment of Piraeus High Availability Controller

=== `haController.image`
Default:: `quay.io/piraeusdatastore/piraeus-ha-controller:v0.1.0`
Valid values:: image ref
Description:: Name of image to use for the HA Controller

=== `haController.replicas`
Default:: `1`
Valid values:: number
Description:: Number of replicas to create for the HA Controller

=== `operator.controller.affinity`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity[affinity]
Description:: Affinity settings for HA Controller pods. Can be used to restrict the pods to specific nodes. The default will expand to:
+
[source,yaml]
----
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: piraeus-op-ha-controller
----

=== `haController.tolerations`
Default:: `[]`
Valid values:: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/[tolerations]
Description:: Tolerations to pass to the HA Controller pods.

=== `haController.resources`
Default:: `{}`
Valid values:: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/[resource requests]
Description:: Resource requests and limits to apply to the HA Controller containers.

=== `haController.podsecuritycontext`
Default:: `{}`
Valid values:: A valid pod-level https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security-context]
Description:: Override for the default security context passed to the HA Controller pods. See <<_global_setsecuritycontext>>
