# This YAML file contains all RBAC objects that are necessary to run a
# CSI controller pod
#
# This file was created by looking at the documentation for:
# node-driver-registrar v1.3.0: https://github.com/kubernetes-csi/node-driver-registrar/tree/v1.3.0#required-permissions
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-node
  namespace: {{ .Release.Namespace }}
---
# Cluster permissions for openshift installations
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-node
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-node
subjects:
  - kind: ServiceAccount
    name: csi-node
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-node
