{{- if .Values.haController.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "operator.fullname" . }}-ha-controller
  namespace: {{ .Release.Namespace }}
{{- if .Values.haController.customAnnotations }}
  annotations:
{{- with .Values.haController.customAnnotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ template "operator.fullname" . }}-ha-controller
{{- if .Values.haController.customLabels }}
{{- with .Values.haController.customLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  replicas: {{ .Values.haController.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "operator.fullname" . }}-ha-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "operator.fullname" . }}-ha-controller
{{- if .Values.haController.customLabels }}
{{- with .Values.haController.customLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
{{- if .Values.haController.customAnnotations }}
      annotations:
{{- with .Values.haController.customAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
    spec:
      serviceAccountName: ha-controller
      initContainers:
        - name: wait-for-api
          image: {{ .Values.haController.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          command:
            - /linstor-wait-until
            - api-online
          env:
{{ include "linstor-env" . | indent 12 }}
{{- if .Values.haController.resources }}
          resources:
{{ toYaml .Values.haController.resources | indent 12 }}
{{- end}}
      containers:
        - name: controller
          image: {{ .Values.haController.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          args:
            - --leader-election=true
            - --leader-election-lease-name=$(NAME)
            - --leader-election-namespace=$(NAMESPACE)
            - --v=5
          env:
{{ include "linstor-env" . | indent 12 }}
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
{{- if .Values.haController.resources }}
          resources:
{{ toYaml .Values.haController.resources | indent 12 }}
{{- end}}
{{- if .Values.drbdRepoCred }}
      imagePullSecrets:
        - name: {{ .Values.drbdRepoCred | quote }}
{{- end }}
{{- if .Values.haController.tolerations }}
      tolerations:
{{ toYaml .Values.haController.tolerations | indent 8 }}
{{- end }}
      affinity:
{{- if .Values.haController.affinity }}
{{ toYaml .Values.haController.affinity | indent 8 }}
{{- else }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ template "operator.fullname" . }}-ha-controller
{{- end }}
      securityContext:
{{- if .Values.haController.podsecuritycontext }}
{{ .Values.podsecuritycontext | toYaml | indent 8 }}
{{- else }}
{{ include "operator.defaultpodsecuritycontext" $ | indent 8 }}
{{- end }}
{{- end }}
