{{/*
Update check to make sure no legacy settings are used
*/}}
{{- if .Values.operator.controllerSet -}}
  {{ fail "Detected use of legacy key 'operator.controllerSet'. Use 'operator.controller' instead" }}
{{- end -}}

{{- if .Values.operator.nodeSet -}}
  {{ fail "Detected use of legacy key 'operator.nodeSet'. Use 'operator.satelliteSet' instead" }}
{{- end -}}

{{- if .Values.operator.satelliteSet.drbdKernelModuleInjectionMode -}}
  {{ fail "Detected use of legacy key 'operator.satelliteSet.drbdKernelModuleInjectionMode'. Use 'operator.satelliteSet.kernelModuleInjectionMode' instead" }}
{{- end -}}

{{- if .Values.operator.satelliteSet.kernelModImage -}}
  {{ fail "Detected use of legacy key 'operator.satelliteSet.kernelModImage'. Use 'operator.satelliteSet.kernelModuleInjectionImage' instead" }}
{{- end -}}
