apiVersion: v1
kind: Service
metadata:
  name: {{ include "piraeus-operator.fullname" . }}-controller-manager-metrics-service
  labels:
  {{- include "piraeus-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
  {{- include "piraeus-operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 443
      targetPort: 8443
