apiVersion: piraeus.linbit.com/v1
kind: LinstorController
metadata:
  name: {{ template "operator.fullname" . }}-cs
spec:
  priorityClassName: {{ .Values.priorityClassName | default "" | quote }}
  dbConnectionURL:  {{ .Values.operator.controller.dbConnectionURL | default (print "etcd://" .Release.Name "-etcd:2379") }}
  luksSecret: {{ .Values.operator.controller.luksSecret }}
  sslSecret: {{ .Values.operator.controller.sslSecret }}
  dbCertSecret: {{ .Values.operator.controller.dbCertSecret | default "" }}
  dbUseClientCert: {{ .Values.operator.controller.dbUseClientCert }}
  drbdRepoCred: {{ .Values.drbdRepoCred | quote }}
  controllerImage: {{ .Values.operator.controller.controllerImage }}
  imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
  linstorHttpsControllerSecret: {{ .Values.linstorHttpsControllerSecret | quote }}
  linstorHttpsClientSecret: {{ .Values.linstorHttpsClientSecret | quote }}
  affinity: {{ .Values.operator.controller.affinity | toJson }}
  tolerations: {{ .Values.operator.controller.tolerations | toJson}}
  resources: {{ .Values.operator.controller.resources | toJson }}
  replicas: {{ .Values.operator.controller.replicas }}
