apiVersion: piraeus.linbit.com/v1alpha1
kind: LinstorNodeSet
metadata:
  name: {{ template "operator.fullname" . }}-ns
spec:
  priorityClassName: {{ template "operator.fullname" . }}-cs-priority-class
  drbdKernelModuleInjectionMode: {{ .Values.operator.nodeSet.spec.drbdKernelModuleInjectionMode }}
  drbdRepoCred: {{ .Values.drbdRepoCred }}
  satelliteImage: {{ .Values.operator.nodeSet.spec.satelliteImage }}
  satelliteVersion: {{ .Values.operator.nodeSet.spec.satelliteVersion }}
  kernelModImage: {{ .Values.operator.nodeSet.spec.kernelModImage }}
  kernelModVersion: {{ .Values.operator.nodeSet.spec.kernelModVersion }}
  storagePools:
    {{- if .Values.operator.nodeSet.spec.lvmPools }}
    lvmPools:
{{ toYaml .Values.operator.nodeSet.spec.lvmPools | indent 6 }}
    {{- end }}
    {{- if .Values.operator.nodeSet.spec.lvmThinPools }}
    lvmThinPools:
{{ toYaml .Values.operator.nodeSet.spec.lvmThinPools | indent 6 }}
    {{- end }}
