apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "operator.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "operator.fullname" . }}-operator
{{- if .Values.operator.customLabels }}
{{- with .Values.operator.customLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- if .Values.operator.customAnnotations }}
  annotations:
{{- with .Values.operator.customAnnotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name: {{ template "operator.fullname" . }}-operator
  template:
    metadata:
      labels:
        name: {{ template "operator.fullname" . }}-operator
{{- if .Values.operator.customLabels }}
{{- with .Values.operator.customLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
{{- if .Values.operator.customAnnotations }}
      annotations:
{{- with .Values.operator.customAnnotations }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
    spec:
      serviceAccountName: {{ template "operator.fullname" . }}
      securityContext:
{{- if .Values.operator.podsecuritycontext }}
{{ toYaml .Values.operator.podsecuritycontext | indent 8 }}
{{- else }}
{{ include "operator.defaultpodsecuritycontext" $ | indent 8 }}
{{- end }}
      containers:
        - name: piraeus-operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          {{- with .Values.operator.args }}
          args:
          {{- range $k, $v := . }}
            - "--{{ kebabcase $k }}={{ $v }}"
          {{- end }}
          {{- end }}
          volumeMounts:
            - name: backup-dir
              mountPath: /run/linstor-backups
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ template "operator.fullname" . }}-operator
          readinessProbe:
            httpGet:
              port: 8081
              path: /readyz
          livenessProbe:
            httpGet:
              port: 8081
              path: /healthz
          resources:
{{ .Values.operator.resources | toYaml | indent 12}}
        {{- with .Values.operator.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: backup-dir
          emptyDir: {}
        {{- with .Values.operator.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- if .Values.drbdRepoCred }}
      imagePullSecrets:
        - name: {{ .Values.drbdRepoCred | quote }}
{{- end }}
      tolerations: {{ toJson .Values.operator.tolerations }}
{{- if .Values.operator.affinity }}
      affinity:
{{ toYaml .Values.operator.affinity | indent 8 }}
{{- else}}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  name: {{ template "operator.fullname" . }}-operator
{{- end }}
