{{- if .Values.operator.controller.enabled }}
apiVersion: piraeus.linbit.com/v1
kind: LinstorController
metadata:
  name: {{ template "operator.fullname" . }}-cs
  namespace: {{ .Release.Namespace }}
spec:
  priorityClassName: {{ .Values.priorityClassName | default "" | quote }}
  # TODO: switch to k8s db by default
  dbConnectionURL:  {{ .Values.operator.controller.dbConnectionURL | default (print "etcd://" .Release.Name "-etcd:2379") }}
{{- if .Values.operator.controller.luksSecret }}
  luksSecret: {{ .Values.operator.controller.luksSecret }}
{{- else }}
  luksSecret: {{ template "operator.fullname" . }}-passphrase
{{- end}}
  sslSecret: {{ include "controller.sslSecretName" . | quote }}
  dbCertSecret: {{ .Values.operator.controller.dbCertSecret | default "" }}
  dbUseClientCert: {{ .Values.operator.controller.dbUseClientCert }}
  drbdRepoCred: {{ .Values.drbdRepoCred | quote }}
  controllerImage: {{ .Values.operator.controller.controllerImage }}
  imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
  linstorHttpsControllerSecret: {{ include "controller.httpsSecretName" . | quote }}
  linstorHttpsClientSecret: {{ include "client.httpsSecretName" . | quote }}
{{- if .Values.operator.controller.affinity }}
  affinity: {{ .Values.operator.controller.affinity | toJson }}
{{- end }}
  tolerations: {{ .Values.operator.controller.tolerations | toJson}}
  resources: {{ .Values.operator.controller.resources | toJson }}
  replicas: {{ .Values.operator.controller.replicas }}
  {{- if .Values.operator.controller.additionalEnv }}
  additionalEnv: {{ .Values.operator.controller.additionalEnv | toJson }}
  {{- end }}
  {{- if .Values.operator.controller.additionalProperties }}
  additionalProperties: {{ .Values.operator.controller.additionalProperties | toJson }}
  {{- end }}
  {{- if .Values.operator.controller.logLevel }}
  logLevel: {{ .Values.operator.controller.logLevel | quote }}
  {{- end }}
  {{- if .Values.operator.controller.httpBindAddress }}
  httpBindAddress: {{ .Values.operator.controller.httpBindAddress | quote }}
  {{- else if (include "controller.sslSecretName" .) }}
  httpBindAddress: "127.0.0.1"
  {{- end }}
  {{- if .Values.operator.controller.httpsBindAddress }}
  httpsBindAddress: {{ .Values.operator.controller.httpsBindAddress | quote }}
  {{- end }}
  {{- if .Values.operator.controller.sidecars }}
  sidecars: {{ .Values.operator.controller.sidecars | toJson }}
  {{- end }}
  {{- if .Values.operator.controller.extraVolumes }}
  extraVolumes: {{ .Values.operator.controller.extraVolumes | toJson }}
  {{- end }}
{{- end }}
