{{- if .Values.operator.controller.enabled }}
apiVersion: piraeus.linbit.com/v1
kind: LinstorController
metadata:
  name: {{ template "operator.fullname" . }}-cs
  namespace: {{ .Release.Namespace }}
spec:
  priorityClassName: {{ .Values.priorityClassName | default "" | quote }}
  # TODO: switch to k8s db by default
  dbConnectionURL:  {{ .Values.operator.controller.dbConnectionURL | default (print "etcd://" .Release.Name "-etcd:2379") }}
{{- if .Values.operator.controller.luksSecret }}
  luksSecret: {{ .Values.operator.controller.luksSecret }}
{{- else }}
  luksSecret: {{ template "operator.fullname" . }}-passphrase
{{- end}}
  sslSecret: {{ .Values.operator.controller.sslSecret }}
  dbCertSecret: {{ .Values.operator.controller.dbCertSecret | default "" }}
  dbUseClientCert: {{ .Values.operator.controller.dbUseClientCert }}
  drbdRepoCred: {{ .Values.drbdRepoCred | quote }}
  controllerImage: {{ .Values.operator.controller.controllerImage }}
  imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
  linstorHttpsControllerSecret: {{ .Values.linstorHttpsControllerSecret | quote }}
  linstorHttpsClientSecret: {{ .Values.linstorHttpsClientSecret | quote }}
{{- if .Values.operator.controller.affinity }}
  affinity: {{ .Values.operator.controller.affinity | toJson }}
{{- end }}
  tolerations: {{ .Values.operator.controller.tolerations | toJson}}
  resources: {{ .Values.operator.controller.resources | toJson }}
  replicas: {{ .Values.operator.controller.replicas }}
  {{- if .Values.operator.controller.additionalEnv }}
  additionalEnv: {{ .Values.operator.controller.additionalEnv | toJson }}
  {{- end }}
  {{- if .Values.operator.controller.additionalProperties }}
  additionalProperties: {{ .Values.operator.controller.additionalProperties | toJson }}
  {{- end }}
  {{- if .Values.operator.controller.logLevel }}
  logLevel: {{ .Values.operator.controller.logLevel | quote }}
  {{- end }}
---
{{- if not .Values.operator.controller.luksSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "operator.fullname" . }}-passphrase
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
data:
{{- /* We have to be careful not to override the original secret value, otherwise encrypted data could be lost forever */}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (printf "%s-passphrase" ( include "operator.fullname" . )) }}
{{- if $secret }}
  MASTER_PASSPHRASE: {{ $secret.data.MASTER_PASSPHRASE | quote }}
{{- else }}
  MASTER_PASSPHRASE: {{ .Values.operator.controller.masterPassphrase | default (randAlphaNum 40) | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
