{{- if .Values.operator.satelliteSet.enabled }}
apiVersion: piraeus.linbit.com/v1
kind: LinstorSatelliteSet
metadata:
  name: {{ template "operator.fullname" . }}-ns
  namespace: {{ .Release.Namespace }}
spec:
  priorityClassName: {{ .Values.priorityClassName | default "" | quote }}
  sslSecret: {{ .Values.operator.satelliteSet.sslSecret }}
  drbdRepoCred: {{ .Values.drbdRepoCred | quote }}
  imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
  satelliteImage: {{ .Values.operator.satelliteSet.satelliteImage }}
  linstorHttpsClientSecret: {{ .Values.linstorHttpsClientSecret | quote }}
  controllerEndpoint: {{ template "controller.endpoint" . }}
  automaticStorageType: {{ .Values.operator.satelliteSet.automaticStorageType | default "None" | quote }}
  affinity: {{ .Values.operator.satelliteSet.affinity | toJson }}
  tolerations: {{ .Values.operator.satelliteSet.tolerations | toJson}}
  resources: {{ .Values.operator.satelliteSet.resources | toJson }}
  monitoringImage: {{ .Values.operator.satelliteSet.monitoringImage | quote }}
  kernelModuleInjectionMode: {{ .Values.operator.satelliteSet.kernelModuleInjectionMode | quote }}
  kernelModuleInjectionImage: {{ .Values.operator.satelliteSet.kernelModuleInjectionImage | quote }}
  kernelModuleInjectionResources: {{ .Values.operator.satelliteSet.kernelModuleInjectionResources | toJson }}
  {{- if .Values.operator.satelliteSet.kernelModuleInjectionAdditionalSourceDirectory }}
  kernelModuleInjectionAdditionalSourceDirectory: {{ .Values.operator.satelliteSet.kernelModuleInjectionAdditionalSourceDirectory | quote }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.storagePools }}
  storagePools:
{{ toYaml .Values.operator.satelliteSet.storagePools | indent 4 }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.additionalEnv }}
  additionalEnv: {{ .Values.operator.satelliteSet.additionalEnv | toJson }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.logLevel }}
  logLevel: {{ .Values.operator.satelliteSet.logLevel | quote }}
  {{- end }}
{{- end }}
