apiVersion: piraeus.linbit.com/v1alpha1
kind: LinstorSatelliteSet
metadata:
  name: {{ template "operator.fullname" . }}-ns
spec:
  priorityClassName: {{ .Values.priorityClassName | default "" | quote }}
  sslSecret: {{ .Values.operator.satelliteSet.sslSecret }}
  drbdKernelModuleInjectionMode: {{ .Values.operator.satelliteSet.drbdKernelModuleInjectionMode }}
  drbdRepoCred: {{ .Values.drbdRepoCred }}
  imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
  satelliteImage: {{ .Values.operator.satelliteSet.satelliteImage }}
  kernelModImage: {{ .Values.operator.satelliteSet.kernelModImage }}
  linstorHttpsClientSecret: {{ .Values.linstorHttpsClientSecret | quote }}
  controllerEndpoint: {{ template "controller.endpoint" . }}
  automaticStorageType: {{ .Values.operator.satelliteSet.automaticStorageType | default "None" | quote }}
  affinity: {{ .Values.operator.satelliteSet.affinity | toJson }}
  tolerations: {{ .Values.operator.satelliteSet.tolerations | toJson}}
  resources: {{ .Values.operator.satelliteSet.resources | toJson }}
  kernelModuleInjectionResources: {{ .Values.operator.satelliteSet.kernelModuleInjectionResources | toJson }}
  {{- if .Values.operator.satelliteSet.storagePools }}
  storagePools:
{{ toYaml .Values.operator.satelliteSet.storagePools | indent 4 }}
  {{- end }}
