apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "operator.fullname" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "operator.fullname" . }}-operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      name: {{ template "operator.fullname" . }}-operator
  template:
    metadata:
      labels:
        name: {{ template "operator.fullname" . }}-operator
    spec:
      serviceAccountName: {{ template "operator.fullname" . }}
      securityContext:
{{- if .Values.operator.podsecuritycontext }}
{{ toYaml .Values.operator.podsecuritycontext | indent 8 }}
{{- else }}
{{ include "operator.defaultpodsecuritycontext" $ | indent 8 }}
{{- end }}
      containers:
        - name: piraeus-operator
          image: {{ .Values.operator.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "piraeus-operator"
          resources:
{{ .Values.operator.resources | toYaml | indent 12}}
{{- if .Values.drbdRepoCred }}
      imagePullSecrets:
        - name: {{ .Values.drbdRepoCred | quote }}
{{- end }}
      tolerations: {{ toJson .Values.operator.tolerations }}
{{- if .Values.operator.affinity }}
      affinity:
{{ toYaml .Values.operator.affinity | indent 8 }}
{{- else}}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  name: {{ template "operator.fullname" . }}-operator
{{- end }}
