apiVersion: piraeus.linbit.com/v1alpha1
kind: LinstorNodeSet
metadata:
  name: {{ template "operator.fullname" . }}-ns
spec:
  priorityClassName: {{ .Values.priorityClassName | default "" | quote }}
  sslSecret: {{ .Values.operator.nodeSet.sslSecret }}
  drbdKernelModuleInjectionMode: {{ .Values.operator.nodeSet.drbdKernelModuleInjectionMode }}
  drbdRepoCred: {{ .Values.drbdRepoCred }}
  satelliteImage: {{ .Values.operator.nodeSet.satelliteImage }}
  kernelModImage: {{ .Values.operator.nodeSet.kernelModImage }}
  linstorHttpsClientSecret: {{ .Values.linstorHttpsClientSecret | quote }}
  {{- if empty .Values.linstorHttpsClientSecret }}
  controllerEndpoint: http://{{ template "operator.fullname" . }}-cs.{{ .Release.Namespace }}.svc:3370
  {{- else }}
  controllerEndpoint: https://{{ template "operator.fullname" . }}-cs.{{ .Release.Namespace }}.svc:3371
  {{- end }}
  automaticStorageType: {{ .Values.operator.nodeSet.automaticStorageType | default "None" | quote }}
  {{- if .Values.operator.nodeSet.storagePools }}
  storagePools:
{{ toYaml .Values.operator.nodeSet.storagePools | indent 4 }}
  {{- end }}
