{{- if .Values.operator.satelliteSet.enabled }}
apiVersion: piraeus.linbit.com/v1
kind: LinstorSatelliteSet
metadata:
  name: {{ template "operator.fullname" . }}-ns
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "operator.fullname" . }}-ns
{{- if .Values.operator.satelliteSet.customLabels }}
{{- with .Values.operator.satelliteSet.customLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- if .Values.operator.satelliteSet.customAnnotations }}
  annotations:
{{- with .Values.operator.satelliteSet.customAnnotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  priorityClassName: {{ .Values.priorityClassName | default "" | quote }}
  sslSecret: {{ include "satelliteSet.sslSecretName" . | quote }}
  drbdRepoCred: {{ .Values.drbdRepoCred | quote }}
  imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
  satelliteImage: {{ .Values.operator.satelliteSet.satelliteImage }}
  linstorHttpsClientSecret: {{ include "client.httpsSecretName" . | quote }}
  controllerEndpoint: {{ template "controller.endpoint" . }}
  automaticStorageType: {{ .Values.operator.satelliteSet.automaticStorageType | default "None" | quote }}
  affinity: {{ .Values.operator.satelliteSet.affinity | toJson }}
  tolerations: {{ .Values.operator.satelliteSet.tolerations | toJson}}
  resources: {{ .Values.operator.satelliteSet.resources | toJson }}
  monitoringImage: {{ .Values.operator.satelliteSet.monitoringImage | quote }}
  kernelModuleInjectionMode: {{ .Values.operator.satelliteSet.kernelModuleInjectionMode | quote }}
  kernelModuleInjectionImage: {{ .Values.operator.satelliteSet.kernelModuleInjectionImage | quote }}
  kernelModuleInjectionResources: {{ .Values.operator.satelliteSet.kernelModuleInjectionResources | toJson }}
  {{- if .Values.operator.satelliteSet.kernelModuleInjectionAdditionalSourceDirectory }}
  kernelModuleInjectionAdditionalSourceDirectory: {{ .Values.operator.satelliteSet.kernelModuleInjectionAdditionalSourceDirectory | quote }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.kernelModuleInjectionExtraVolumeMounts }}
  kernelModuleInjectionExtraVolumeMounts: {{ .Values.operator.satelliteSet.kernelModuleInjectionExtraVolumeMounts | toJson }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.storagePools }}
  storagePools:
{{ toYaml .Values.operator.satelliteSet.storagePools | indent 4 }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.additionalEnv }}
  additionalEnv: {{ .Values.operator.satelliteSet.additionalEnv | toJson }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.logLevel }}
  logLevel: {{ .Values.operator.satelliteSet.logLevel | quote }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.sidecars }}
  sidecars: {{ .Values.operator.satelliteSet.sidecars | toJson }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.extraVolumes }}
  extraVolumes: {{ .Values.operator.satelliteSet.extraVolumes | toJson }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.monitoringBindAddress }}
  monitoringBindAddress: {{ .Values.operator.satelliteSet.monitoringBindAddress | quote }}
  {{- end }}
  {{- if .Values.operator.satelliteSet.mountDrbdResourceDirectoriesFromHost }}
  mountDrbdResourceDirectoriesFromHost: {{ .Values.operator.satelliteSet.mountDrbdResourceDirectoriesFromHost }}
  {{- end }}
{{- end }}
