{{- $fullName := include "operator.fullname" . -}}
{{- $cn := printf "%s-cs" $fullName -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- if (eq .Values.linstorHttpsMethod "helm") }}
{{- $ca := genCA (printf "%s-ca" $fullName) 3650 -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "controller.httpsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  {{- with genSignedCert $cn (list "::1" "127.0.0.1") (list $cn $altName1 $altName2 "localhost") 3650 $ca }}
  tls.crt: {{ b64enc .Cert }}
  tls.key: {{ b64enc .Key }}
  ca.crt: {{ b64enc $ca.Cert }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "client.httpsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: kubernetes.io/tls
data:
  {{- with genSignedCert (printf "%s-client" $fullName) nil nil 3650 $ca }}
  tls.crt: {{ b64enc .Cert }}
  tls.key: {{ b64enc .Key }}
  ca.crt: {{ b64enc $ca.Cert }}
  {{- end }}
{{- else if (eq .Values.linstorHttpsMethod "cert-manager") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "controller.httpsSecretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ template "controller.httpsSecretName" . }}
  commonName: {{ $cn }}
  ipAddresses:
  - "::1"
  - "127.0.0.1"
  dnsNames:
  - {{ $cn }}
  - {{ $altName1 }}
  - {{ $altName2 }}
  - localhost
  duration: 87600h # 3650d
  usages:
  - "signing"
  - "key encipherment"
  - "server auth"
  issuerRef:
    name: {{ $fullName }}-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "client.httpsSecretName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ template "client.httpsSecretName" . }}
  commonName: {{ $cn }}-client
  duration: 87600h # 3650d
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: {{ $fullName }}-ca-issuer
    kind: Issuer
    group: cert-manager.io
{{- else if (not (eq (.Values.linstorHttpsMethod | default "manual") "manual"))  }}
{{- fail ".Values.linstorHttpsMethod is not set to <manual|helm|cert-manager>" }}
{{- end }}
