apiVersion: piraeus.linbit.com/v1alpha1
kind: LinstorNodeSet
metadata:
  name: {{ template "operator.fullname" . }}-ns
spec:
  priorityClassName: {{ template "operator.fullname" . }}-cs-priority-class
  drbdKernelModuleInjectionMode: {{ .Values.operator.nodeSet.drbdKernelModuleInjectionMode }}
  drbdRepoCred: {{ .Values.drbdRepoCred }}
  satelliteImage: {{ .Values.operator.nodeSet.satelliteImage }}
  kernelModImage: {{ .Values.operator.nodeSet.kernelModImage }}
  {{- if .Values.operator.nodeSet.storagePools }}
  storagePools:
{{ toYaml .Values.operator.nodeSet.storagePools | indent 4 }}
  {{- end }}
