apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "piraeus-operator.fullname" . }}-csi-controller
spec:
  selector:
    matchLabels:
      app: {{ template "piraeus-operator.fullname" . }}-csi-controller
      role: {{ template "piraeus-operator.fullname" . }}-csi
  serviceName: {{ template "piraeus-operator.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "piraeus-operator.fullname" . }}-csi-controller
        role: {{ template "piraeus-operator.fullname" . }}-csi
    spec:
      priorityClassName: {{ template "piraeus-operator.fullname" . }}-csi-priority-class
      serviceAccount: {{ template "piraeus-operator.fullname" . }}-csi-controller-sa
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          args:
            - "--provisioner=linstor.csi.linbit.com"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--feature-gates=Topology=false"
            - "--connection-timeout=4m"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=4m"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v1.0.1
          args:
            - "--connection-timeout=4m"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-cluster-driver-registrar
          image: quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1
          args:
            - "--v=5"
            - "--pod-info-mount-version=\"v1\""
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: linstor-csi-plugin
          image: quay.io/piraeusdatastore/piraeus-csi:v0.7.3
          # image: drbd.io/linstor-csi:v0.7.2
          # imagePullSecrets:
          #   - name: {{ .Values.repoCreds }}
          args:
            - "--csi-endpoint=$(CSI_ENDPOINT)"
            - "--node=$(KUBE_NODE_NAME)"
            - "--linstor-endpoint=$(LINSTOR_IP)"
            - "--log-level=debug"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LINSTOR_IP
              value: http://{{ .Release.Name }}-cs:3370
              # value: http://{{ .Release.Name }}-{{ template "piraeus-operator.fullname" . }}:3370
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
