{{- define "bind-role" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Prefix }}-{{ .Role }}
  namespace: {{ .Namespace }}
roleRef:
  kind: Role
  name: {{ .Role }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Authorize specific service accounts:
  {{- range .Accounts }}
  - kind: ServiceAccount
    name: {{ . }}
    namespace: {{ $.Namespace }}
  {{- end }}
{{- end -}}

{{ if .Values.psp.unprivilegedRole }}
---
{{ $unprivAccounts := list (include "operator.fullname" .) "linstor-controller" "csi-controller" "stork-scheduler-account" "stork-account" "snapshot-controller" "etcd" }}
{{ template "bind-role" (dict "Prefix" .Release.Name "Role" .Values.psp.unprivilegedRole "Namespace" .Release.Namespace "Accounts" $unprivAccounts) }}
---
{{ end }}
{{ if .Values.psp.privilegedRole }}
---
{{ $privAccounts := list "linstor-satellite" "csi-node" }}
{{ template "bind-role" (dict "Prefix" .Release.Name "Role" .Values.psp.privilegedRole "Namespace" .Release.Namespace "Accounts" $privAccounts) }}
---
{{ end }}
