# This YAML file contains all RBAC objects that are necessary to run a
# LINSTOR satellite pod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-satellite
  namespace: {{ .Release.Namespace }}
