# This YAML file contains all RBAC objects that are necessary to run a
# LINSTOR satellite pod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-satellite
  namespace: {{ .Release.Namespace }}
---
  # Cluster permissions for openshift installations
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linstor-satellite
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linstor-satellite
subjects:
  - kind: ServiceAccount
    name: linstor-satellite
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linstor-satellite
