// +build !ignore_autogenerated

/*
Piraeus Operator
Copyright 2019 LINBIT USA, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusControllerSet) DeepCopyInto(out *PiraeusControllerSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusControllerSet.
func (in *PiraeusControllerSet) DeepCopy() *PiraeusControllerSet {
	if in == nil {
		return nil
	}
	out := new(PiraeusControllerSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiraeusControllerSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusControllerSetList) DeepCopyInto(out *PiraeusControllerSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PiraeusControllerSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusControllerSetList.
func (in *PiraeusControllerSetList) DeepCopy() *PiraeusControllerSetList {
	if in == nil {
		return nil
	}
	out := new(PiraeusControllerSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiraeusControllerSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusControllerSetSpec) DeepCopyInto(out *PiraeusControllerSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusControllerSetSpec.
func (in *PiraeusControllerSetSpec) DeepCopy() *PiraeusControllerSetSpec {
	if in == nil {
		return nil
	}
	out := new(PiraeusControllerSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusControllerSetStatus) DeepCopyInto(out *PiraeusControllerSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusControllerSetStatus.
func (in *PiraeusControllerSetStatus) DeepCopy() *PiraeusControllerSetStatus {
	if in == nil {
		return nil
	}
	out := new(PiraeusControllerSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusNodeSet) DeepCopyInto(out *PiraeusNodeSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusNodeSet.
func (in *PiraeusNodeSet) DeepCopy() *PiraeusNodeSet {
	if in == nil {
		return nil
	}
	out := new(PiraeusNodeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiraeusNodeSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusNodeSetList) DeepCopyInto(out *PiraeusNodeSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PiraeusNodeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusNodeSetList.
func (in *PiraeusNodeSetList) DeepCopy() *PiraeusNodeSetList {
	if in == nil {
		return nil
	}
	out := new(PiraeusNodeSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiraeusNodeSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusNodeSetSpec) DeepCopyInto(out *PiraeusNodeSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusNodeSetSpec.
func (in *PiraeusNodeSetSpec) DeepCopy() *PiraeusNodeSetSpec {
	if in == nil {
		return nil
	}
	out := new(PiraeusNodeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusNodeSetStatus) DeepCopyInto(out *PiraeusNodeSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusNodeSetStatus.
func (in *PiraeusNodeSetStatus) DeepCopy() *PiraeusNodeSetStatus {
	if in == nil {
		return nil
	}
	out := new(PiraeusNodeSetStatus)
	in.DeepCopyInto(out)
	return out
}
