/*
Piraeus Operator
Copyright 2019 LINBIT USA, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusNodeSet) DeepCopyInto(out *PiraeusNodeSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusNodeSet.
func (in *PiraeusNodeSet) DeepCopy() *PiraeusNodeSet {
	if in == nil {
		return nil
	}
	out := new(PiraeusNodeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiraeusNodeSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusNodeSetList) DeepCopyInto(out *PiraeusNodeSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PiraeusNodeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusNodeSetList.
func (in *PiraeusNodeSetList) DeepCopy() *PiraeusNodeSetList {
	if in == nil {
		return nil
	}
	out := new(PiraeusNodeSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiraeusNodeSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusNodeSetSpec) DeepCopyInto(out *PiraeusNodeSetSpec) {
	*out = *in
	if in.StoragePools != nil {
		in, out := &in.StoragePools, &out.StoragePools
		*out = new(StoragePools)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusNodeSetSpec.
func (in *PiraeusNodeSetSpec) DeepCopy() *PiraeusNodeSetSpec {
	if in == nil {
		return nil
	}
	out := new(PiraeusNodeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiraeusNodeSetStatus) DeepCopyInto(out *PiraeusNodeSetStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SatelliteStatuses != nil {
		in, out := &in.SatelliteStatuses, &out.SatelliteStatuses
		*out = make(map[string]*SatelliteStatus, len(*in))
		for key, val := range *in {
			var outVal *SatelliteStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(SatelliteStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiraeusNodeSetStatus.
func (in *PiraeusNodeSetStatus) DeepCopy() *PiraeusNodeSetStatus {
	if in == nil {
		return nil
	}
	out := new(PiraeusNodeSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatelliteStatus) DeepCopyInto(out *SatelliteStatus) {
	*out = *in
	if in.StoragePoolStatuses != nil {
		in, out := &in.StoragePoolStatuses, &out.StoragePoolStatuses
		*out = make(map[string]*StoragePoolStatus, len(*in))
		for key, val := range *in {
			var outVal *StoragePoolStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(StoragePoolStatus)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatelliteStatus.
func (in *SatelliteStatus) DeepCopy() *SatelliteStatus {
	if in == nil {
		return nil
	}
	out := new(SatelliteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolLVM) DeepCopyInto(out *StoragePoolLVM) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolLVM.
func (in *StoragePoolLVM) DeepCopy() *StoragePoolLVM {
	if in == nil {
		return nil
	}
	out := new(StoragePoolLVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolLVMThin) DeepCopyInto(out *StoragePoolLVMThin) {
	*out = *in
	out.StoragePoolLVM = in.StoragePoolLVM
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolLVMThin.
func (in *StoragePoolLVMThin) DeepCopy() *StoragePoolLVMThin {
	if in == nil {
		return nil
	}
	out := new(StoragePoolLVMThin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolStatus) DeepCopyInto(out *StoragePoolStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolStatus.
func (in *StoragePoolStatus) DeepCopy() *StoragePoolStatus {
	if in == nil {
		return nil
	}
	out := new(StoragePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePools) DeepCopyInto(out *StoragePools) {
	*out = *in
	if in.LVMPools != nil {
		in, out := &in.LVMPools, &out.LVMPools
		*out = make([]*StoragePoolLVM, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StoragePoolLVM)
				**out = **in
			}
		}
	}
	if in.LVMThinPools != nil {
		in, out := &in.LVMThinPools, &out.LVMThinPools
		*out = make([]*StoragePoolLVMThin, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StoragePoolLVMThin)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePools.
func (in *StoragePools) DeepCopy() *StoragePools {
	if in == nil {
		return nil
	}
	out := new(StoragePools)
	in.DeepCopyInto(out)
	return out
}
