---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: piraeus-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - piraeus-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - piraeus.linbit.com
  resources:
  - '*'
  - linstorcontrollersets
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: piraeus-operator
subjects:
- kind: ServiceAccount
  name: piraeus-operator
roleRef:
  kind: Role
  name: piraeus-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: piraeus-operator
---
apiVersion: scheduling.k8s.io/v1 # v1beta1 for 1.13
kind: PriorityClass
metadata:
  name: "piraeus-cs-priority-class"
value: 1000010
globalDefault: false
description: "Priority class for piraeus controller"
---
apiVersion: scheduling.k8s.io/v1 # v1beta1 for 1.13
kind: PriorityClass
metadata:
  name: piraeus-ns-priority-class
value: 1000000
globalDefault: false
description: "Priority class for piraeus satellite(s)"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piraeus-operator
  labels:
    name: piraeus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: piraeus-operator
  template:
    metadata:
      labels:
        name: piraeus-operator
    spec:
      serviceAccountName: piraeus-operator
      containers:
        - name: piraeus-operator
          image: "quay.io/piraeusdatastore/piraeus-operator:latest"
          command:
          - piraeus-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "piraeus-operator"
      imagePullSecrets:
      - name: drbdiocred
---
