linstorSslMethod: "cert-manager"
linstorHttpsMethod: "cert-manager"
operator:
  args:
    createMonitoring: false
    metricsBindAddress: "127.0.0.1:8080"
  sidecars:
    - name: kube-rbac-proxy
      image: quay.io/brancz/kube-rbac-proxy:v0.11.0
      args:
        - "--upstream=http://127.0.0.1:8080"
        - "--config-file=/etc/kube-rbac-proxy/piraeus-operator.yaml"
        - "--secure-listen-address=$(KUBE_RBAC_PROXY_LISTEN_ADDRESS):8383"
        - "--client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        - "--v=2"
        - "--logtostderr=true"
      ports:
      - containerPort: 8080
      env:
        - name: KUBE_RBAC_PROXY_LISTEN_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumeMounts:
        - name: rbac-proxy-config
          mountPath: /etc/kube-rbac-proxy
  extraVolumes:
    - name: rbac-proxy-config
      configMap:
        name: piraeus-rbac-proxy
  controller:
    httpBindAddress: "127.0.0.1"
    sidecars:
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.11.0
        args:
          - "--upstream=http://127.0.0.1:3370"
          - "--config-file=/etc/kube-rbac-proxy/linstor-controller.yaml"
          - "--secure-listen-address=$(KUBE_RBAC_PROXY_LISTEN_ADDRESS):3370"
          - "--client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          - "--v=2"
          - "--logtostderr=true"
        env:
          - name: KUBE_RBAC_PROXY_LISTEN_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: rbac-proxy-config
            mountPath: /etc/kube-rbac-proxy
    extraVolumes:
      - name: rbac-proxy-config
        configMap:
          name: piraeus-rbac-proxy
  satelliteSet:
    monitoringBindAddress: "127.0.0.1"
    sidecars:
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.11.0
        args:
          - "--upstream=http://127.0.0.1:9942"
          - "--config-file=/etc/kube-rbac-proxy/linstor-node.yaml"
          - "--secure-listen-address=$(KUBE_RBAC_PROXY_LISTEN_ADDRESS):9942"
          - "--client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          - "--v=2"
          - "--logtostderr=true"
        env:
          - name: KUBE_RBAC_PROXY_LISTEN_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
          - name: rbac-proxy-config
            mountPath: /etc/kube-rbac-proxy
    extraVolumes:
      - name: rbac-proxy-config
        configMap:
          name: piraeus-rbac-proxy
