package tolerations

import (
	"slices"

	corev1 "k8s.io/api/core/v1"

	"github.com/piraeusdatastore/piraeus-ha-controller/pkg/metadata"
)

var (
	// DefaultDaemonSetTolerations are the tolerations added to a DaemonSet by default.
	DefaultDaemonSetTolerations = []corev1.Toleration{
		// The relevant section:
		// https://github.com/kubernetes/kubernetes/blob/8f5a33768a388db03c0b50480bc0d5a134a78ef2/pkg/controller/daemon/util/daemonset_util.go#L47-L102
		{
			Key:      corev1.TaintNodeNotReady,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoExecute,
		},
		{
			Key:      corev1.TaintNodeUnreachable,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoExecute,
		},
		{
			Key:      corev1.TaintNodeDiskPressure,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoSchedule,
		},
		{
			Key:      corev1.TaintNodeMemoryPressure,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoSchedule,
		},
		{
			Key:      corev1.TaintNodePIDPressure,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoSchedule,
		},
		{
			Key:      corev1.TaintNodeUnschedulable,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoSchedule,
		},
		{
			Key:      corev1.TaintNodeNetworkUnavailable,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoSchedule,
		},
	}
	// HAControllerTolerations tolerate taints generated by the HA Controller.
	HAControllerTolerations = []corev1.Toleration{
		{
			Key:      metadata.NodeForceIoErrorTaint,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoSchedule,
		},
		{
			Key:      metadata.NodeLostQuorumTaint,
			Operator: corev1.TolerationOpExists,
			Effect:   corev1.TaintEffectNoSchedule,
		},
	}

	// FailOverTimeOut is the number of seconds the LINSTOR Controller should tolerate fail-over worthy Taints.
	FailOverTimeOut = int64(30)
	// LinstorControllerTolerations tolerate fail-over relevant taints only up to FailOverTimeOut
	LinstorControllerTolerations = []corev1.Toleration{
		{
			Key:               corev1.TaintNodeUnreachable,
			Operator:          corev1.TolerationOpExists,
			Effect:            corev1.TaintEffectNoExecute,
			TolerationSeconds: &FailOverTimeOut,
		},
		{
			Key:               corev1.TaintNodeNotReady,
			Operator:          corev1.TolerationOpExists,
			Effect:            corev1.TaintEffectNoExecute,
			TolerationSeconds: &FailOverTimeOut,
		},
	}

	// NoScheduleToleration tolerates all NoSchedule taints.
	NoScheduleToleration = []corev1.Toleration{
		{
			Effect:   corev1.TaintEffectNoSchedule,
			Operator: corev1.TolerationOpExists,
		},
	}
)

// MergeTolerations combines all the given tolerations.
//
// An earlier matching toleration is always replaced.
func MergeTolerations(tolerations ...[]corev1.Toleration) []corev1.Toleration {
	if len(tolerations) == 0 {
		return nil
	}

	// defensive copy
	result := slices.Clone(tolerations[0])

	for _, toAdd := range tolerations[1:] {
		for i := range toAdd {
			updated := false

			for j := range result {
				if toAdd[i].MatchToleration(&result[j]) {
					// Unconditionally replace the toleration, "later toleration wins"
					result[j] = toAdd[i]
					updated = true
				}
			}

			// Add it to the list if we haven't added our toleration.
			if !updated {
				result = append(result, toAdd[i])
			}
		}
	}

	return result
}
