---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linstor-controller
  labels:
    app.kubernetes.io/component: linstor-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: linstor-controller
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: linstor-controller
      labels:
        app.kubernetes.io/component: linstor-controller
    spec:
      initContainers:
        - name: run-migration
          image: linstor-controller
          args:
            - runMigration
          env:
            - name: K8S_AWAIT_ELECTION_ENABLED
              value: "1"
            - name: K8S_AWAIT_ELECTION_NAME
              value: "linstor-controller"
            - name: "K8S_AWAIT_ELECTION_LOCK_NAME"
              value: "linstor-controller"
            - name: "K8S_AWAIT_ELECTION_LOCK_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_AWAIT_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /run/migration
              name: migration
            - mountPath: /etc/linstor
              name: etc-linstor
              readOnly: true
            - mountPath: /tmp
              name: tmp
      containers:
        - name: linstor-controller
          image: linstor-controller
          args:
            - startController
          env:
            - name: JAVA_OPTS
              value: '-Djdk.tls.acknowledgeCloseNotify=true'
            - name: K8S_AWAIT_ELECTION_ENABLED
              value: "1"
            - name: K8S_AWAIT_ELECTION_NAME
              value: "linstor-controller"
            - name: "K8S_AWAIT_ELECTION_LOCK_NAME"
              value: "linstor-controller"
            - name: "K8S_AWAIT_ELECTION_LOCK_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_AWAIT_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: api
              containerPort: 3370
              protocol: TCP
          livenessProbe:
            httpGet:
              port: api
              path: /health
          startupProbe:
            httpGet:
              port: api
              path: /health
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/log/linstor-controller
              name: var-log-linstor-controller
            - mountPath: /etc/linstor
              name: etc-linstor
              readOnly: true
            - mountPath: /tmp
              name: tmp
      enableServiceLinks: false
      serviceAccountName: linstor-controller
      priorityClassName: system-node-critical
      volumes:
        - name: etc-linstor
          configMap:
            name: linstor-controller-config
        - name: var-log-linstor-controller
          emptyDir: { }
        - name: tmp
          emptyDir: { }
        - name: migration
          emptyDir: { }
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - effect: NoSchedule
          key: drbd.linbit.com/lost-quorum
        - effect: NoSchedule
          key: drbd.linbit.com/force-io-error
