---
apiVersion: v1
kind: Service
metadata:
  name: linstor-controller
  labels:
    app.kubernetes.io/component: linstor-controller
spec:
  selector:
    app.kubernetes.io/component: linstor-controller
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: 3370
      name: api
      protocol: TCP
