---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linstor-controller
  labels:
    app.kubernetes.io/component: linstor-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linstor-controller
subjects:
  - kind: ServiceAccount
    name: linstor-controller
