---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: linstor-controller
  labels:
    app.kubernetes.io/component: linstor-controller
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch
