---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gencert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gencert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gencert
subjects:
  - kind: ServiceAccount
    name: gencert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gencert
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gencert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gencert
subjects:
  - kind: ServiceAccount
    name: gencert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gencert
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    resourceNames:
      - validating-webhook-configuration
    verbs:
      - get
      - list
      - watch
      - update
