---
# Source: piraeus/templates/ha-controller-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ha-controller
  namespace: default
---
# Source: piraeus/templates/ha-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ha-controller
rules:
  - verbs:
      - list
      - watch
      - delete
    apiGroups:
      - ""
    resources:
      - pods
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - list
      - watch
---
# Source: piraeus/templates/ha-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ha-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ha-controller
subjects:
  - kind: ServiceAccount
    name: ha-controller
    namespace: default
---
# Source: piraeus/templates/ha-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ha-controller
  namespace: default
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
---
# Source: piraeus/templates/ha-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ha-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ha-controller
subjects:
  - kind: ServiceAccount
    name: ha-controller
    namespace: default
