---
# Source: piraeus/templates/satellite-rbac.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linstor-satellite
  namespace: default
---
# Source: piraeus/templates/satellite-rbac.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linstor-satellite
  namespace: default
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use
---
# Source: piraeus/templates/satellite-rbac.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linstor-satellite
subjects:
  - kind: ServiceAccount
    name: linstor-satellite
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linstor-satellite
---
# Source: piraeus/templates/satellite-rbac.yml
# This YAML file contains all RBAC objects that are necessary to run a
# LINSTOR satellite pod
---
# Source: piraeus/templates/satellite-rbac.yml
# Cluster permissions for openshift installations
