---
# Source: piraeus/charts/csi-snapshotter/templates/deployment.yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: snapshot-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snapshot-controller
  template:
    metadata:
      labels:
        app: snapshot-controller
    spec:
      serviceAccountName: snapshot-controller
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: snapshot-controller
          image: quay.io/k8scsi/snapshot-controller:v2.1.0
          args:
            - "--v=5"
            - "--leader-election=true"
          imagePullPolicy: "IfNotPresent"
          resources:
            {}
---
# Source: piraeus/charts/csi-snapshotter/templates/deployment.yaml
# This YAML file shows how to deploy the snapshot controller

  # The snapshot controller implements the control loop for CSI snapshot functionality.
  # It should be installed as part of the base Kubernetes distribution in an appropriate
  # namespace for components implementing base system functionality. For installing with
  # Vanilla Kubernetes, kube-system makes sense for the namespace.
