name: Build piraeus-operator
on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: login to registry
        if: ${{ github.event_name != 'pull_request' }}
        env:
          QUAYIO_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          QUAYIO_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login --username=${QUAYIO_USERNAME} --password-stdin quay.io <<< "${QUAYIO_PASSWORD}"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/piraeusdatastore/piraeus-operator
          tags: |
            type=sha
            type=raw,value=latest
            type=ref,event=tag
            type=ref,event=pr
      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./build/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
