name: build and push docker image
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      OPERATOR_SDK_VERSION: v0.16.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.0.3
      - uses: actions/cache@v1
        with:
          path: ~/operator-sdk/bin/
          key: operator-sdk-${{ env.OPERATOR_SDK_VERSION }}
      - name: setup operator-sdk
        run: |
          if [ ! -x ~/operator-sdk/bin/operator-sdk ]; then
            mkdir -p ~/operator-sdk/bin/
            curl -L https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk-${OPERATOR_SDK_VERSION}-x86_64-linux-gnu > ~/operator-sdk/bin/operator-sdk
            chmod +x ~/operator-sdk/bin/operator-sdk
          fi
          echo "::add-path::${HOME}/operator-sdk/bin/"
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Build with operator-sdk
        run: operator-sdk build quay.io/piraeusdatastore/piraeus-operator:latest
      - name: Push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io
          repository: piraeusdatastore/piraeus-operator
          dockerfile: ./build/Dockerfile
          # master -> latest
          # tag -> tag
          # pull request -> pr-{pull request}
          tag_with_ref: true
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
