name: check and build piraeus-operator
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          only-new-issues: true
          # Lints are more guidelines than actual rules
          args: --issues-exit-code=0

  checks:
    runs-on: ubuntu-latest
    env:
      # These hooks will run separately in github actions
      SKIP: golangci-lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - uses: actions/setup-python@v4
      - name: Run pre-commit checks on changes files
        uses: pre-commit/action@v3.0.0
