name: go-test
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  go-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Setup Go environment
        uses: actions/setup-go@v2.0.3
      - uses: actions/checkout@v2
      # Caching
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
      # Tests
      - name: Run unit tests
        run:  go test ./...
