name: release.yml
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build release resources
        run: |
          make manifest.yaml changes.md chart
      - uses: softprops/action-gh-release@v2
        with:
          body_path: changes.md
          draft: true
          files: |
            manifest.yaml
            piraeus-*.tgz
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Charts to GHCR
        run: |
          helm push piraeus-*.tgz oci://ghcr.io/${{ github.repository }}
